/* ========================================================
   FILE: js/data-usrah.js
   FUNGSI: Menyimpan database awal / default untuk kelompok Usrah.
   ======================================================== */

export const dataAwalUsrah = {
  "Kamal": [
    "ADITYA PUTRA IBRAHIM", "AIRLANGGA AZKA ABQORI", "AQIELA MARSYAH", 
    "BRILLY HANDRIAN", "DARREN ATHAYA", "DZIKRI MUDHOFFAR", 
    "ELLENO QUTHBIE HERMAWAN", "FADIL NURHALIM", "GABRIEL AL FATIH", 
    "HADINATA SAPUTRA", "MIKO VAJAR", "M. ALMISKY PRATAMA", 
    "M. AQIL RIDHO", "M. IZAM SAPUTRA", "M. SYAKIR HUTABARAT", 
    "M. YASIR AL FAZAR JHIRA", "M. ZIYAD ZHAZHA", "RAFA", 
    "WAHYU REYDINATA", "NIZAM KABISAT", "JUANDA NUR ILHAM", 
    "M. DIRGATAMA", "DAFFA AL MUSYARI", "MOHAMMAD IKHSAN HAIRULI", 
    "REYFAS RAMADHAN", "FALIZH DAFFA QATRUNNADA", "HAFIDZ AL ROZI", 
    "CANZA RYANDA HUTASUHUT", "NAJMIHADI SYAUQII TAMAAM", "EZA FEBRI AL FADZRI"
  ],
  "Favian": [
    "ABDULLAH MUKTI HAFIDZALLAH", "AHMAD RIYADI", "AKBAR PRAYOGA", 
    "ALIF MUHAMMAD YUSUF", "ALVIN HERFIANTINO", "ANDES AFENDRA", 
    "BASRI AL HAZIQ ZULFAHMI", "AHMAD MAULANA", "DANANG PRASDITYA SANTOSO", 
    "DEDI SETIADI", "DIKKI KURNIAWAN", "FAKHRI AL MUZAKKI", 
    "FEBRI GHALIH AL FAROBI", "GHOZY FATURRAHMAN", "ILHAM MUKMIN AL FARABI", 
    "M. AL FALAH", "M. FAQIH HAFIDZALLAH", "M. FIRAAS AL INSYIROH", 
    "MUHAMMAD ALLAM NUR HUSHAIN", "M. RAID MAHRUS", "M. RIJALUL KAMIL", 
    "NABIL NAJMI", "RADEN AZAA PANCA PUTRA", "RAFI RAMADHAN", 
    "SATRIO ABIMAYU", "TEGAR HIDAYAT", "VERY SYACH", 
    "WAFII FADHLURROHMAN", "ZAHIR ZIBRAN", "ZULFAKIH HAERUNNASIHIN"
  ],
  "Regen": [
    "ANGGA PRATAMA PUTRA", "KI AGUS MUHAMMAD ABDULLAH SHIDDIQ AGTSALI", 
    "MIKA RAHIEL YUSUF", "PRAWIRO PUJO TUNGGAL JATI", "M. XAVI NF", 
    "REYNALDI MALIK IBRAHIM ALFARIDZI", "FAHRIE OKTAVIRANO FITRIS", 
    "FARAZH SAYYID PUTRA KENEGA", "LUTHFAN ADZAKI", "MARFEL SAPUTRA", 
    "MELDI NOVRIANSYAH", "ALIF SAMUDRA", "ARYA DIFA ALSYA", 
    "FAUZAN IBNI JABAR", "HAFIDZ ALRIZKY", "M. ABIL IRWANSYAH", 
    "M. FADHIL BUANA", "M. FAISAL FIKRIANSYAH", "NAUFAL AKBAR ALKHATIRI", 
    "QHEIZAN ALQIZA ARISDA", "REZFY FAKHRYAZKA", "SYAHRUL RAMADHAN", 
    "ROID AFDAL", "ROHADIN FIRDAUS AL QAUSAR", "RENAL MARTIN", 
    "RAKA SEPTIAN", "NAFIS", "M. USAMAH", "MUHAMAD YUSUF ARROSIYD", 
    "MAHESA AULIA GIFFARI", "M. ARYA MAHDI WAFI EL-FAUZANI", "ILHAM", 
    "IHZA TRINANDI", "HABIB RAMADHAN", "FAHRY AKBAR RAMDHANI", 
    "CAHYIS ISZAM", "ANUGRAH PRATAMA", "AHMAD FARHAAN"
  ],
  "Fatimah": [
    "QELZA RAMADHANI ATH THAHIRAH", "ASHIFA FITRI RAMADHONI", 
    "ADIBA AILA KHANZA", "AISYAH NUR KHALIFAH", "NYAYU MARLITSA ARDHANI", 
    "WILDA", "WINDY WINDARI", "AISYAH NURUL AULIA", "NESSYA RAMADHANY", 
    "AMIRAH BALQIS RAHADATUL A'ISYAH", "EARLYTA ARSYFA SALSABILA", 
    "DAFIA NAFLA SYAKIRA", "ANISYA SEPTIANI"
  ],
  "Evita": [
    "BILQIS NUR ANISAH", "JESSICA PUTRY AYRA", "GHENIS ANDIENTIAZ", 
    "DINA RUHAYAH", "PITRI RAMADANI", "GRINNETA NALANI PUTRI", 
    "INAYAH NOURAH ANINDYA", "SHELENA", "FITRAH KIRANA"
  ]
};