import{initializeApp,getApps}from'https://www.gstatic.com/firebasejs/10.7.1/firebase-app.js';
import{getDatabase,ref,get,set}from'https://www.gstatic.com/firebasejs/10.7.1/firebase-database.js';
const C=window.cahayaRoleContext,$=id=>document.getElementById(id),ROOT='cahaya_app/naqib_teladan_harian';
if(!C||!['NAQIB','NAQIBAH'].includes(C.activeRole))throw new Error('ROLE_CONTEXT_REQUIRED');C.assertCurrent();
const app=getApps().length?getApps()[0]:initializeApp(window.CAHAYA_CONFIG.firebase),db=getDatabase(app),user=(()=>{try{return JSON.parse(localStorage.getItem('cahayaCurrentUser')||'{}')||{}}catch{return{}}})(),name=String(user.label||user.nama||user.displayName||user.username||'Naqib').trim(),key=String(user.username||name).trim().toLowerCase().replace(/[^a-z0-9_-]+/g,'_'),jakarta=()=>{const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}`},date=jakarta(),path=`${ROOT}/${key}/${date}`;let data=null,saving=false;
$('roleChip').textContent=C.activeRole==='NAQIBAH'?'Naqibah':'Naqib';$('dateChip').textContent=new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Jakarta',weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date());
$('backBtn').onclick=()=>{const P=parent!==window?parent:window;if(typeof P.openAuthorizedMenu==='function')P.openAuthorizedMenu('menu-home');else location.href='../main-dashboard.html'};
function toast(message,type=''){const e=$('toast');e.textContent=message;e.className='c2-toast show '+type;clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.className='c2-toast',2500)}
const num=(id,label,icon)=>`<article class="c2-card counter"><span class="counter-icon">${icon}</span><b>${label}</b><div class="stepper"><button type="button" data-step="-1" data-target="${id}" aria-label="Kurangi ${label}">−</button><output id="${id}">${Number(data?.[id]||0)}</output><button type="button" data-step="1" data-target="${id}" aria-label="Tambah ${label}">+</button></div></article>`;
const yesno=(id,title,text)=>`<article class="c2-card check-card"><h3>${title}</h3><p>${text}</p><div class="c2-options"><label class="c2-option"><input type="radio" name="${id}" value="BELUM" ${data?.[id]!=='SUDAH'?'checked':''}><span>Belum</span></label><label class="c2-option"><input type="radio" name="${id}" value="SUDAH" ${data?.[id]==='SUDAH'?'checked':''}><span>Sudah</span></label></div></article>`;
function render(){const exists=Boolean(data);$('content').innerHTML=`<section class="c2-section"><div class="c2-section-head"><span class="c2-kicker">ANGKA HARI INI</span><h2>Kehadiran bersama santri</h2></div><div class="counter-grid">${num('shalatBerjamaah','Shalat Jamaah','◷')}${num('menemaniMakan','Menemani Makan','♨')}${num('menemaniWirid','Menemani Wirid','☾')}</div></section><section class="c2-section"><div class="c2-section-head"><span class="c2-kicker">KETELADANAN PRIBADI</span><h2>Sudahkah saya memberi contoh?</h2></div><div class="check-list">${yesno('kamarRapi','Kamar Naqib Bersih/Rapi','Saya sudah membersihkan atau merapikan kamar Naqib hari ini.')}${yesno('penampilanRapi','Penampilan Rapi & Bersih','Saya menjalankan tugas dengan penampilan yang rapi dan bersih.')}${yesno('siapLebihDahulu','Siap Lebih Dahulu Sebelum Memerintah','Saya sudah siap sebelum meminta santri untuk siap.')}</div><div class="c2-actions"><button class="c2-primary" id="saveBtn" type="button">${exists?'Perbarui Catatan Hari Ini':'Simpan Catatan Hari Ini'}</button></div>${exists?'<div class="saved-note">Catatan hari ini sudah ada. Menyimpan kembali akan memperbarui record yang sama.</div>':''}</section>`;document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{const out=$(b.dataset.target),max=b.dataset.target==='shalatBerjamaah'?5:10;out.textContent=Math.max(0,Math.min(max,Number(out.textContent)+Number(b.dataset.step)))});$('saveBtn').onclick=save}
function value(name){return document.querySelector(`input[name="${name}"]:checked`)?.value||'BELUM'}
async function save(){if(saving)return;C.assertCurrent();saving=true;$('saveBtn').disabled=true;$('saveBtn').textContent='Menyimpan…';const now=new Date().toISOString(),payload={versi:'V1',tanggal:date,naqib:name,naqibKey:key,role:C.activeRole,unit:C.unit,shalatBerjamaah:Number($('shalatBerjamaah').textContent),menemaniMakan:Number($('menemaniMakan').textContent),menemaniWirid:Number($('menemaniWirid').textContent),kamarRapi:value('kamarRapi'),penampilanRapi:value('penampilanRapi'),siapLebihDahulu:value('siapLebihDahulu'),waktuSimpan:data?.waktuSimpan||now,waktuUpdate:now};try{await set(ref(db,path),payload);data=payload;render();toast('Catatan teladan hari ini tersimpan.','success')}catch(e){console.error(e);$('saveBtn').disabled=false;$('saveBtn').textContent=data?'Perbarui Catatan Hari Ini':'Simpan Catatan Hari Ini';toast('Catatan belum tersimpan. Coba kembali.','error')}finally{saving=false}}
try{const snap=await get(ref(db,path));C.assertCurrent();data=snap.exists()?snap.val():null;render()}catch(e){console.error(e);data=null;render();toast('Data hari ini belum dapat dimuat.','error')}
