const assert=require('node:assert/strict');
const C=require('../js/counselor-case-v2.js');
const R=require('../js/role-system-v2.js');
function row(date,code='BOLOS_PROGRAM',student='Ahmad',extra={}){return C.normalizeCase({tanggal:date,tipe:'Lapor Pelanggaran',dilaporkan:student,kodePelanggaran:code,...extra},date+code)}
assert.equal(C.routeCase(row('2026-09-18'),[]).level,'PEMULA');
assert.equal(C.routeCase(row('2026-09-18','TERLAMBAT_PROGRAM'),[]).level,'PEMULA');
assert.equal(C.routeCase(row('2026-09-18','KEBERSIHAN'),[]).level,'PEMULA');
assert.deepEqual(C.routeCase(row('2026-09-18','MORAL'),[]),{level:'MADYA',reason:'MORAL'});
assert.equal(C.routeCase(row('2026-09-18','LAIN','Ahmad',{severity:'BERAT'}),[]).level,'MADYA');
assert.equal(C.routeCase(row('2026-09-18','LAIN','Ahmad',{severity:'KRITIS'}),[]).level,'MADYA');
const consecutive=[row('2026-09-16'),row('2026-09-17'),row('2026-09-18')];assert.equal(C.routeCase(consecutive[2],consecutive).reason,'THREE_CONSECUTIVE_DAYS');
const broken=[row('2026-09-15'),row('2026-09-17'),row('2026-09-18')];assert.equal(C.routeCase(broken[2],broken).level,'PEMULA');
assert.equal(C.routeCase(row('2026-09-18','BOLOS_PROGRAM','Ahmad',{caseV2:{escalation:{reason:'Kompleks'}}}),[]).reason,'MANUAL_ESCALATION');
assert.equal(C.pointFor('BIMBINGAN'),0);assert.equal(C.pointFor('RINGAN'),-25);assert.equal(C.pointFor('SEDANG'),-50);assert.equal(C.pointFor('BERAT'),-100);assert.equal(C.pointFor('KRITIS'),-200);
assert.deepEqual(C.nfdk({niat:2,frekuensi:2,dampak:2,kondisi:1}),{score:7,severity:'KRITIS'});
const legacy=R.resolveSession({roleSystemVersion:2,username:'x',roles:['KONSELOR'],defaultRole:'KONSELOR',assignments:{KONSELOR:{unit:'PUTRI',level:'MUDA'}}},{getItem(){return''},setItem(){}});assert.equal(legacy.activeAssignment.level,'MADYA');
assert.equal(C.weekKey(new Date('2026-09-18T12:00:00Z')),'2026-09-14');
assert.deepEqual(C.calendarRange('TODAY','2026-09-18'),{start:'2026-09-18',end:'2026-09-18'});
assert.deepEqual(C.calendarRange('WEEK','2026-09-18'),{start:'2026-09-14',end:'2026-09-18'});
assert.deepEqual(C.calendarRange('MONTH','2026-09-18'),{start:'2026-09-01',end:'2026-09-18'});
assert.equal(C.validRange('2026-08-29','2026-09-02'),true);assert.equal(C.validRange('2026-09-18','2026-09-01'),false);
assert.equal(C.jakartaDate(new Date('2026-09-17T17:30:00Z')),'2026-09-18');
const escalated=row('2026-09-18','BOLOS_PROGRAM','Ahmad',{caseV2:{escalation:{reason:'Kompleks',note:'Fakta baru',escalatedByName:'Pemula',escalatedAt:'2026-09-18T10:00:00Z'},higherEscalation:{targetRole:'SUPERVISOR',requestedByName:'Madya',requestedAt:'2026-09-18T11:00:00Z',reason:'Butuh arahan',summary:'Ringkas',decisionNeeded:'Arahan',urgency:'SEGERA',response:{respondedBy:'Supervisor',respondedAt:'2026-09-18T12:00:00Z',decision:'Lanjutkan',instruction:'Pantau'}}}});
assert.deepEqual(C.timeline(escalated).filter(x=>x.type.includes('ESKALASI')||x.type.includes('RESPONS')).map(x=>x.label),['Kasus dieskalasi ke Konselor Madya','Meminta arahan Supervisor','Arahan Supervisor diterima']);
assert(C.timeline(escalated).some(x=>x.type==='DILANJUTKAN_MADYA'&&x.label==='Dilanjutkan Konselor Madya'));
const pendingSupervisor=row('2026-09-18','MORAL','Ahmad',{unit:'PUTRA',statusPenanganan:'MENUNGGU_ARAHAN_SUPERVISOR',caseV2:{status:'MENUNGGU_ARAHAN_SUPERVISOR',routeLevel:'MADYA',claim:{assignedCounselorId:'madya'},higherEscalation:{targetRole:'SUPERVISOR',requestedAt:'2026-09-18T11:00:00Z'}}});
const supervisor={activeRole:'SUPERVISOR',activeAssignment:{unit:'PUTRA',supervisedRoles:['KONSELOR']}};
assert.equal(C.canHigherAuthorityRespond(supervisor,pendingSupervisor),true);
assert.equal(C.canHigherAuthorityRespond({activeRole:'DIREKTUR',activeAssignment:{unit:'ALL'}},pendingSupervisor),false);
assert.equal(C.canHigherAuthorityRespond({activeRole:'MANAJER',activeAssignment:{unit:'PUTRA',managedRoles:['KONSELOR']}},pendingSupervisor),false);
const supervisorPatch=C.higherResponsePatch(supervisor,pendingSupervisor,{instruction:'Lanjutkan pendampingan',note:'Pantau pekanan'},{username:'spv',name:'Supervisor'},'2026-09-18T13:00:00Z');
assert.equal(supervisorPatch.status,'ARAHAN_SUPERVISOR_DITERIMA');assert.equal(supervisorPatch.response.respondedRole,'SUPERVISOR');
assert.equal(pendingSupervisor.caseV2.claim.assignedCounselorId,'madya');
const pendingDirector=row('2026-09-18','MORAL','Ahmad',{unit:'PUTRA',statusPenanganan:'MENUNGGU_KEPUTUSAN_DIREKTUR',caseV2:{status:'MENUNGGU_KEPUTUSAN_DIREKTUR',routeLevel:'MADYA',claim:{assignedCounselorId:'madya'},higherEscalation:{targetRole:'DIREKTUR',requestedAt:'2026-09-18T11:00:00Z'}}});
const director={activeRole:'DIREKTUR',activeAssignment:{unit:'ALL'}};
const directorPatch=C.higherResponsePatch(director,pendingDirector,{decision:'Disetujui','instruction':'Laksanakan sesuai SOP'},{username:'dir',name:'Direktur'},'2026-09-18T13:30:00Z');
assert.equal(directorPatch.status,'KEPUTUSAN_DIREKTUR_DITERIMA');assert.equal(directorPatch.response.respondedRole,'DIREKTUR');
console.log('counselor-v2: ok');
