const fs=require('node:fs'),assert=require('node:assert/strict'),R=require('../js/role-system-v2.js'),N=require('../js/role-navigation-v2.js');
const read=p=>fs.readFileSync(p,'utf8'),home=read('home-dapur.html'),app=read('dapur/app.html'),guide=read('dapur/panduan.html'),logic=read('js/dapur-app-v2.js'),procurement=read('js/dapur-procurement-v2.js'),material=read('js/dapur-material-v2.js');
const profile={username:'dapur',roleSystemVersion:2,roles:['DAPUR'],defaultRole:'DAPUR',assignments:{DAPUR:{unit:'PUTRA'}}},session=R.resolveSession(profile,{getItem:()=>null,setItem(){}});
assert.equal(R.homeFor('DAPUR'),'home-dapur.html?v=275');
assert.equal(N.canAccessRoute(session,'home-dapur.html','menu-home').ok,true);
assert.equal(N.canAccessRoute(session,'dapur/app.html?view=logbook','menu-dashboard-operasional').ok,true);
assert.equal(N.canAccessRoute(session,'dapur/panduan.html','menu-panduan-kerja').ok,true);
const naqib=R.resolveSession({roleSystemVersion:2,roles:['NAQIB'],defaultRole:'NAQIB',assignments:{NAQIB:{unit:'PUTRA'}}},{getItem:()=>null,setItem(){}});
assert.equal(N.canAccessRoute(naqib,'dapur/app.html?view=logbook','menu-dashboard-operasional').ok,false);
assert.equal((home.match(/class="dv-feature"/g)||[]).length,4);
for(const text of['Jurnal Makan','Daftar Belanja Besok','Penerimaan Bahan','Menu Makan Harian'])assert(home.includes(text));
for(const meal of['Pagi','Siang','Sore'])assert(logic.includes(meal));
for(const item of['Kompor bersih','Meja bersih','Lantai dipel','Tempat sampah dikosongkan','Saluran air bersih','Peralatan tersusun','Kulkas bersih'])assert(logic.includes(item));
assert(logic.includes("LOG_PATH='cahaya_app/logbook_dapur_harian'"));assert(logic.includes("CHECK_PATH='cahaya_app/checklist_kebersihan_dapur'"));
assert(logic.includes("status==='FINAL'"));assert(logic.includes("orderByChild('tanggal')"));assert(logic.includes('startAt(from),endAt(to)'));
assert(app.includes('id="mealPicker"'));assert(app.includes('id="mealEditor" hidden'));assert(!app.includes('shoppingList'));assert(!app.includes('receivedList'));
for(const path of ['cahaya_app/daftar_belanja_dapur','cahaya_app/penerimaan_bahan_dapur'])assert(procurement.includes(path));
for(const status of ['SESUAI','DIUBAH','TIDAK_TEREALISASI'])assert(procurement.includes(status));
assert(material.includes('canEditMenu=isSupervisorDapur'));assert(material.includes('Hanya Supervisor Dapur yang dapat menyusun menu.'));
for(const day of ['Senin','Selasa','Rabu','Kamis','Jumat','Sabtu','Ahad'])assert(material.includes(day));
assert(material.includes('name="hari"'));assert(!material.includes('name="tanggal" type="date" value="${today()}" required></label><label class="dv-field">Waktu Makan'));
assert(procurement.includes('Download Daftar Belanja'));assert(procurement.includes('window.html2pdf'));assert(!procurement.includes('Tampilan Screenshot'));
assert(procurement.includes('LAPORAN SUPERVISOR'));assert(procurement.includes('loadReport()'));
assert(!home.includes('Pemakaian Bahan'));assert(!read('js/role-menu-v2.js').includes("['usage','Pemakaian Bahan'"));
assert(!app.includes('7 hari terakhir'));assert(!app.includes('30 hari terakhir'));assert(guide.includes('DAPUR → SUPERVISOR'));assert(!guide.includes('Manager Dapur'));
for(const item of['Menanyakan kepada PJ Dapur jumlah porsi','Menjaga kualitas rasa dan kematangan makanan','Memeriksa ketersediaan bahan makanan','Membuat daftar kebutuhan belanja','Mengusulkan perbaikan menu','pengecekan kondisi peralatan dapur','Daftar Belanja Besok','setiap hari Kamis'])assert(guide.includes(item));
console.log('dapur-v2: ok');
