const fs=require('node:fs'),assert=require('node:assert/strict'),R=require('../js/role-system-v2.js'),N=require('../js/role-navigation-v2.js');
const read=p=>fs.readFileSync(p,'utf8'),home=read('home-dapur.html'),app=read('dapur/app.html'),guide=read('dapur/panduan.html'),logic=read('js/dapur-app-v2.js');
const profile={username:'dapur',roleSystemVersion:2,roles:['DAPUR'],defaultRole:'DAPUR',assignments:{DAPUR:{unit:'PUTRA'}}},session=R.resolveSession(profile,{getItem:()=>null,setItem(){}});
assert.equal(R.homeFor('DAPUR'),'home-dapur.html?v=225');
assert.equal(N.canAccessRoute(session,'home-dapur.html','menu-home').ok,true);
assert.equal(N.canAccessRoute(session,'dapur/app.html?view=logbook','menu-dashboard-operasional').ok,true);
assert.equal(N.canAccessRoute(session,'dapur/panduan.html','menu-panduan-kerja').ok,true);
const naqib=R.resolveSession({roleSystemVersion:2,roles:['NAQIB'],defaultRole:'NAQIB',assignments:{NAQIB:{unit:'PUTRA'}}},{getItem:()=>null,setItem(){}});
assert.equal(N.canAccessRoute(naqib,'dapur/app.html?view=logbook','menu-dashboard-operasional').ok,false);
assert.equal((home.match(/class="dv-feature"/g)||[]).length,4);
for(const text of['Logbook Hari Ini','Checklist Kebersihan','Riwayat','Panduan Kerja'])assert(home.includes(text));
for(const meal of['Sarapan','Makan Siang','Makan Sore'])assert(logic.includes(meal));
for(const item of['Kompor bersih','Meja bersih','Lantai dipel','Tempat sampah dikosongkan','Saluran air bersih','Peralatan tersusun','Kulkas bersih'])assert(logic.includes(item));
assert(logic.includes("LOG_PATH='cahaya_app/logbook_dapur_harian'"));assert(logic.includes("CHECK_PATH='cahaya_app/checklist_kebersihan_dapur'"));
assert(logic.includes("status==='FINAL'"));assert(logic.includes("orderByChild('tanggal')"));assert(logic.includes('startAt(from),endAt(to)'));
assert.equal((app.match(/Daftar (?:Belanja Bahan|Bahan yang Diterima) <small>Opsional<\/small>/g)||[]).length,2);
assert(!app.includes('7 hari terakhir'));assert(!app.includes('30 hari terakhir'));assert(guide.includes('DAPUR → SUPERVISOR'));assert(!guide.includes('Manager Dapur'));
for(const item of['Menanyakan kepada PJ Dapur jumlah porsi','Menjaga kualitas rasa dan kematangan makanan','Memeriksa ketersediaan bahan makanan','Membuat daftar kebutuhan belanja','Mengusulkan perbaikan menu','pengecekan kondisi peralatan dapur','akhir bulan','setiap hari Kamis'])assert(guide.includes(item));
console.log('dapur-v2: ok');
