const assert=require('node:assert/strict'),fs=require('node:fs');
const R=require('../js/role-system-v2.js'),N=require('../js/role-navigation-v2.js');
const user={username:'director-test',roleSystemVersion:2,roles:['DIREKTUR'],defaultRole:'DIREKTUR',assignments:{DIREKTUR:{unit:'ALL'}}};
const session=R.resolveSession(user,{getItem:()=>null,setItem(){}});
assert.equal(R.homeFor('DIREKTUR',session.activeAssignment),'home-direktur.html?v=240');
assert.equal(R.assignmentFor('DIREKTUR',{}).unit,'ALL');
assert.equal(N.canAccessRoute(session,'pimpinan/direktur-v2.html?view=kpi','menu-kpi-direktur').ok,true);
assert.equal(N.canAccessRoute(session,'pimpinan/direktur-v2.html?view=schedule','menu-jadwal-direktur').ok,true);
const other=R.resolveSession({username:'other',roleSystemVersion:2,roles:['GURU_PONDOK'],defaultRole:'GURU_PONDOK',assignments:{GURU_PONDOK:{unit:'PUTRA',programDomain:'KEPONDOKAN'}}},{getItem:()=>null,setItem(){}});
assert.equal(N.canAccessRoute(other,'pimpinan/direktur-v2.html?view=condition').ok,false);
const home=fs.readFileSync('js/director-home-hub.js','utf8'),workspace=fs.readFileSync('js/director-workspace-v2.js','utf8'),shell=fs.readFileSync('main-dashboard.html','utf8');
assert.doesNotMatch(home,/getDatabase\(|getDocs\(|\bget\(/);
for(const name of ['Kondisi Pesantren','Eskalasi & Keputusan','Target & Arah','Supervisor','Masalah Sistemik','Rekap KPI Supervisor','Perubahan Sistem','Pembinaan Supervisor','Riwayat Keputusan','Panduan Kerja'])assert.match(home,new RegExp(name));
assert.match(workspace,/directorEscalation\/response/);
assert.match(workspace,/supervisorEscalation\/directorEscalation\/response/);
assert.match(workspace,/caseV2\/higherEscalation\/\$\{suffix\}/);
assert.match(workspace,/escalationSources\(from,to,true\)/);
assert.match(workspace,/orderByKey\(\)/);
assert.match(workspace,/errors\?'—':subset\.length/);
assert.match(workspace,/decisions&&!decisions\.errors/);
assert.match(workspace,/partial\?'—':items\.length,'Agenda periode'/);
assert.match(workspace,/await get\(ref\(db,path\)\)/);
const menu=require('../js/role-menu-v2.js');assert.equal(menu.bottom(session,'jadwal'),'menu-jadwal-direktur');assert.equal(menu.bottom(session,'kpi'),'menu-kpi-direktur');
for(const file of ['home-direktur.html','pimpinan/direktur-v2.html','js/director-home-hub.js','js/director-workspace-v2.js','js/role-system-v2.js','js/role-route-registry-v2.js','js/role-navigation-v2.js','main-dashboard.html'])assert.equal(fs.readFileSync(file,'utf8'),fs.readFileSync('docs/'+file,'utf8'),file+' mirror');
console.log('director-v2: routes, zero-read Home, contracts, mirrors ok');
