const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const C=require('../js/penitipan-barang-v2.js');
const root=path.resolve(__dirname,'..');
const sandbox={window:{}};
vm.runInNewContext(fs.readFileSync(path.join(root,'config/master-data.js'),'utf8'),sandbox);
vm.runInNewContext(fs.readFileSync(path.join(root,'js/penitipan-student-ids.js'),'utf8'),sandbox);
const packaged=sandbox.window.CAHAYA_STUDENT_ID_REGISTRY;
const original=JSON.parse(fs.readFileSync(path.join(root,'migration-export/students.json'),'utf8'));
assert.equal(packaged.length,original.length,'static file:// registry mirrors existing identity export');
const roster=C.buildRoster(sandbox.window.CAHAYA_MASTER_DATA.santriByClass,packaged);
const master=Object.entries(sandbox.window.CAHAYA_MASTER_DATA.santriByClass).filter(([kelas])=>/^Kelas\s+\d+\s+(Putra|Putri)$/i.test(kelas)).flatMap(([,names])=>names);
assert.equal(roster.length,new Set(master).size,'every current santri has a stable ID');
assert.equal(new Set(roster.map(x=>x.id)).size,roster.length,'IDs are unique');
for(const name of ['M. UMAR HALIM RAHMAPUTRA','MUHAMMAD FIRAAS AL - INSYIROH','NABILA NUR WAMAWADDA AL- MAIRA'])assert(C.uniqueByName(name,roster),'punctuation-variant student is mapped');
const a=roster.find(x=>x.name==='NAEVA MARNIA'),b=roster.find(x=>x.name==='NAYYA SALSABILLA');
assert(a&&b);
assert.deepEqual(C.linkedStudentIds({namaAnak:a.name},{},{},roster),[a.id]);
assert.deepEqual(C.linkedStudentIds({studentIds:[a.id,b.id]},{},{},roster),[a.id,b.id]);
assert.equal(C.legacyStudent({penerima:a.name,unit:a.unit},roster).id,a.id);
assert.equal(C.legacyStudent({penerima:'NAMA AMBIGU',unit:a.unit},roster),null);
assert.equal(C.statusOf({statusBarang:'SUDAH_DIAMBIL'}),'SUDAH_DISERAHKAN');
assert.equal(C.statusOf({status:'DIPROSES'}),'DIPROSES');
assert.match(C.depositPath({unit:'putri',monthKey:'2026-09',id:'-abc'}),/^penitipan_barang\/putri\/2026-09\/-abc$/);
console.log('Penitipan V2 identity/status contract: OK, roster',roster.length);
