const assert=require('node:assert/strict'),fs=require('node:fs');
const R=require('../js/role-system-v2.js'),N=require('../js/role-navigation-v2.js'),S=require('../js/supervisor-v2-contract.js');
function session(roles,scope){return R.resolveSession({username:'sv-test',roleSystemVersion:2,roles,defaultRole:roles[0],assignments:{[roles[0]]:scope}},{getItem:()=>null,setItem(){}})}
const education={unit:'PUTRA',supervisedRoles:['GURU_PONDOK']},direct={unit:'PUTRI',supervisedRoles:['DAPUR','SARPRAS']},character={unit:'PUTRA',supervisedRoles:['NAQIB','MENTOR_USRAH','KONSELOR']};
assert.deepEqual(S.areas(education),['PENDIDIKAN']);
assert.deepEqual(S.areas(direct),['DAPUR','SARPRAS']);
assert.deepEqual(S.areas(character),['PEMBINAAN_KARAKTER']);
assert.deepEqual(S.areas({...education,divisionIds:['PENDIDIKAN']}),['PENDIDIKAN']);
assert.deepEqual(S.areas({...education,divisionIds:['MEDIA']}),[]);
assert.deepEqual(S.areas({...education,divisionIds:['UNKNOWN']}),[]);
assert.equal(S.allows(education,'DAPUR'),false);
assert.equal(S.allows(education,'PENDIDIKAN','PUTRI'),false);
assert.equal(S.inScope({unit:'PUTRI'},education,'PENDIDIKAN'),false);
assert.equal(S.inScope({unit:'PUTRA'},education,'PENDIDIKAN'),true);
assert.equal(S.inScope({},education,'PENDIDIKAN'),false);
assert.equal(S.inScope({},direct,'DAPUR'),false);
assert.equal(S.inScope({unit:'PUTRI'},direct,'DAPUR'),true);
assert.equal(S.inScope({unit:'PUTRA'},direct,'DAPUR'),false);
assert.equal(S.areas(education).includes('PKBM'),false);
assert.deepEqual(S.dateRange('2026-09-20','WEEK'),{from:'2026-09-14',to:'2026-09-20'});
assert.equal(S.dateOf({tanggal:'2026-09-20',createdAt:'2026-09-19T16:00:00Z'}),'2026-09-20');
assert.equal(R.homeFor('SUPERVISOR',education),'home-supervisor-v2.html?v=239');
const sv=session(['SUPERVISOR'],education),notSupervisor=session(['MANAJER'],{unit:'PUTRA',area:'PENDIDIKAN',managedRoles:['GURU_PONDOK'],programDomain:'KEPONDOKAN'});
assert(R.menusFor('SUPERVISOR',sv.activeAssignment).includes('menu-kpi-supervisor'));
assert(N.canAccessRoute(sv,'home-supervisor-v2.html','menu-home').ok);
assert(N.canAccessRoute(sv,'supervisor/workspace-v2.html?view=divisions','menu-supervisor-v2').ok);
assert(N.canAccessRoute(sv,'supervisor/workspace-v2.html?view=kpi','menu-kpi-supervisor').ok);
assert.equal(N.canAccessRoute(sv,'supervisor/workspace-v2.html?view=divisions&area=MEDIA','menu-supervisor-v2').ok,false);
assert.equal(N.canAccessRoute(sv,'supervisor/workspace-v2.html?view=divisions&area=PENDIDIKAN','menu-supervisor-v2').ok,true);
assert.equal(N.canAccessRoute(notSupervisor,'supervisor/workspace-v2.html?view=kpi').ok,false);
const home=fs.readFileSync('js/supervisor-home-v2.js','utf8'),workspace=fs.readFileSync('js/supervisor-workspace-v2.js','utf8'),shell=fs.readFileSync('main-dashboard.html','utf8');
assert.doesNotMatch(home,/get\(|getDocs\(|getDatabase\(/);
assert.match(home,/Kondisi Divisi/);
assert.match(home,/Rekap KPI Bawahan/);
assert.match(home,/const quick=\[/);
assert.match(home,/const menu=\[/);
assert.match(workspace,/supervisorEscalation\/response/);
assert.match(workspace,/records=\[\.\.\.active,\.\.\.pending\]/);
assert.match(workspace,/const snap=await get\(ref\(db,verifyPath\)\)/);
assert.match(workspace,/selected\?\.id\|\|`sv_\$\{d\.tanggal\}/);
assert.match(workspace,/caseV2\?\.higherEscalation/);
assert.match(workspace,/PEMBANDING_SUPERVISOR/);
assert.match(workspace,/ESKALASI_KE_DIREKTUR/);
assert.match(workspace,/path===PATH\.mediaWeekly\?'weekStart':'tanggal'/);
assert.match(workspace,/readDate\(path,from,to,dateField\)/);
assert.match(workspace,/\$\('filters'\)\.hidden=view==='guide'/);
const menu=require('../js/role-menu-v2.js');assert.equal(menu.bottom(sv,'jadwal'),'menu-supervisor-schedule');assert.equal(menu.bottom(sv,'kpi'),'menu-kpi-supervisor');
for(const p of ['home-supervisor-v2.html','supervisor/workspace-v2.html','js/supervisor-home-v2.js','js/supervisor-workspace-v2.js','js/supervisor-v2-contract.js','js/role-system-v2.js','js/role-route-registry-v2.js','js/role-navigation-v2.js','main-dashboard.html'])assert.equal(fs.readFileSync(p,'utf8'),fs.readFileSync('docs/'+p,'utf8'),p+' mirror');
console.log('supervisor-v2: role, scope, routes, zero-read Home, workflow contracts, mirrors ok');
